EWPP-2885: Update to PHP 8.1.
openeuropa/composite_reference pull request #22
Opened 2022-12-09 08:11 UTC by 22Alexandra

2022-12-12 11:17 UTC, yenyasinn approved these changes, later dismissed

2022-12-12 14:34 UTC, nagyad approved these changes

2022-12-14 13:34 UTC, nagyad requested changes
Let's make a new 2.2.x branch for the target branch.

2022-12-15 12:24 UTC, nagyad approved these changes

2022-12-21 15:16 UTC, brummbar approved these changes

2022-12-21 15:16 UTC, merged